"""Embedded catalog used only when live symbol-directory sources are unavailable."""

FALLBACK_CATALOG = [
    {"ticker": 'GOLD', "company": 'Barrick Mining Corporation', "exchange": 'NYSE', "sector": 'Materials', "asset_type": "STOCK"},
    {"ticker": 'AAPL', "company": 'Apple Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'MSFT', "company": 'Microsoft Corporation', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'NVDA', "company": 'NVIDIA Corporation', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'AMD', "company": 'Advanced Micro Devices, Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'AVGO', "company": 'Broadcom Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'INTC', "company": 'Intel Corporation', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'QCOM', "company": 'QUALCOMM Incorporated', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'MU', "company": 'Micron Technology, Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'AMAT', "company": 'Applied Materials, Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'LRCX', "company": 'Lam Research Corporation', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'KLAC', "company": 'KLA Corporation', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'MRVL', "company": 'Marvell Technology, Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'ADI', "company": 'Analog Devices, Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'NXPI', "company": 'NXP Semiconductors N.V.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'TXN', "company": 'Texas Instruments Incorporated', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'CSCO', "company": 'Cisco Systems, Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'ORCL', "company": 'Oracle Corporation', "exchange": 'NYSE', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'IBM', "company": 'International Business Machines Corporation', "exchange": 'NYSE', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'CRM', "company": 'Salesforce, Inc.', "exchange": 'NYSE', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'NOW', "company": 'ServiceNow, Inc.', "exchange": 'NYSE', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'ADBE', "company": 'Adobe Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'PANW', "company": 'Palo Alto Networks, Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'CRWD', "company": 'CrowdStrike Holdings, Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'FTNT', "company": 'Fortinet, Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'SNOW', "company": 'Snowflake Inc.', "exchange": 'NYSE', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'PLTR', "company": 'Palantir Technologies Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'APP', "company": 'AppLovin Corporation', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'ANET', "company": 'Arista Networks, Inc.', "exchange": 'NYSE', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'DELL', "company": 'Dell Technologies Inc.', "exchange": 'NYSE', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'HPE', "company": 'Hewlett Packard Enterprise Company', "exchange": 'NYSE', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'HPQ', "company": 'HP Inc.', "exchange": 'NYSE', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'SMCI', "company": 'Super Micro Computer, Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'ARM', "company": 'Arm Holdings plc', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'WDC', "company": 'Western Digital Corporation', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'STX', "company": 'Seagate Technology Holdings plc', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
    {"ticker": 'AMZN', "company": 'Amazon.com, Inc.', "exchange": 'NASDAQ', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'TSLA', "company": 'Tesla, Inc.', "exchange": 'NASDAQ', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'WMT', "company": 'Walmart Inc.', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'COST', "company": 'Costco Wholesale Corporation', "exchange": 'NASDAQ', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'TGT', "company": 'Target Corporation', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'HD', "company": 'The Home Depot, Inc.', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'LOW', "company": "Lowe's Companies, Inc.", "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'TJX', "company": 'The TJX Companies, Inc.', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'ROST', "company": 'Ross Stores, Inc.', "exchange": 'NASDAQ', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'NKE', "company": 'NIKE, Inc.', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'MCD', "company": "McDonald's Corporation", "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'SBUX', "company": 'Starbucks Corporation', "exchange": 'NASDAQ', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'CMG', "company": 'Chipotle Mexican Grill, Inc.', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'YUM', "company": 'Yum! Brands, Inc.', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'BKNG', "company": 'Booking Holdings Inc.', "exchange": 'NASDAQ', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'ABNB', "company": 'Airbnb, Inc.', "exchange": 'NASDAQ', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'MAR', "company": 'Marriott International, Inc.', "exchange": 'NASDAQ', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'HLT', "company": 'Hilton Worldwide Holdings Inc.', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'RCL', "company": 'Royal Caribbean Cruises Ltd.', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'CCL', "company": 'Carnival Corporation', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'UBER', "company": 'Uber Technologies, Inc.', "exchange": 'NYSE', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'LYFT', "company": 'Lyft, Inc.', "exchange": 'NASDAQ', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'DASH', "company": 'DoorDash, Inc.', "exchange": 'NASDAQ', "sector": 'Consumer', "asset_type": "STOCK"},
    {"ticker": 'GOOGL', "company": 'Alphabet Inc. Class A', "exchange": 'NASDAQ', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'GOOG', "company": 'Alphabet Inc. Class C', "exchange": 'NASDAQ', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'META', "company": 'Meta Platforms, Inc.', "exchange": 'NASDAQ', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'NFLX', "company": 'Netflix, Inc.', "exchange": 'NASDAQ', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'DIS', "company": 'The Walt Disney Company', "exchange": 'NYSE', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'CMCSA', "company": 'Comcast Corporation', "exchange": 'NASDAQ', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'WBD', "company": 'Warner Bros. Discovery, Inc.', "exchange": 'NASDAQ', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'SPOT', "company": 'Spotify Technology S.A.', "exchange": 'NYSE', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'ROKU', "company": 'Roku, Inc.', "exchange": 'NASDAQ', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'T', "company": 'AT&T Inc.', "exchange": 'NYSE', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'VZ', "company": 'Verizon Communications Inc.', "exchange": 'NYSE', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'TMUS', "company": 'T-Mobile US, Inc.', "exchange": 'NASDAQ', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'JPM', "company": 'JPMorgan Chase & Co.', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'BAC', "company": 'Bank of America Corporation', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'WFC', "company": 'Wells Fargo & Company', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'C', "company": 'Citigroup Inc.', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'GS', "company": 'The Goldman Sachs Group, Inc.', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'MS', "company": 'Morgan Stanley', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'BLK', "company": 'BlackRock, Inc.', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'BX', "company": 'Blackstone Inc.', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'KKR', "company": 'KKR & Co. Inc.', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'SCHW', "company": 'The Charles Schwab Corporation', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'COF', "company": 'Capital One Financial Corporation', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'AXP', "company": 'American Express Company', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'V', "company": 'Visa Inc.', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'MA', "company": 'Mastercard Incorporated', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'PYPL', "company": 'PayPal Holdings, Inc.', "exchange": 'NASDAQ', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'HOOD', "company": 'Robinhood Markets, Inc.', "exchange": 'NASDAQ', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'IBKR', "company": 'Interactive Brokers Group, Inc.', "exchange": 'NASDAQ', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'SOFI', "company": 'SoFi Technologies, Inc.', "exchange": 'NASDAQ', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'CME', "company": 'CME Group Inc.', "exchange": 'NASDAQ', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'ICE', "company": 'Intercontinental Exchange, Inc.', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'SPGI', "company": 'S&P Global Inc.', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'MCO', "company": "Moody's Corporation", "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'BRK-B', "company": 'Berkshire Hathaway Inc.', "exchange": 'NYSE', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'COIN', "company": 'Coinbase Global, Inc.', "exchange": 'NASDAQ', "sector": 'Financial', "asset_type": "STOCK"},
    {"ticker": 'LLY', "company": 'Eli Lilly and Company', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'UNH', "company": 'UnitedHealth Group Incorporated', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'JNJ', "company": 'Johnson & Johnson', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'MRK', "company": 'Merck & Co., Inc.', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'ABBV', "company": 'AbbVie Inc.', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'PFE', "company": 'Pfizer Inc.', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'BMY', "company": 'Bristol-Myers Squibb Company', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'AMGN', "company": 'Amgen Inc.', "exchange": 'NASDAQ', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'GILD', "company": 'Gilead Sciences, Inc.', "exchange": 'NASDAQ', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'VRTX', "company": 'Vertex Pharmaceuticals Incorporated', "exchange": 'NASDAQ', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'REGN', "company": 'Regeneron Pharmaceuticals, Inc.', "exchange": 'NASDAQ', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'ISRG', "company": 'Intuitive Surgical, Inc.', "exchange": 'NASDAQ', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'TMO', "company": 'Thermo Fisher Scientific Inc.', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'DHR', "company": 'Danaher Corporation', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'ABT', "company": 'Abbott Laboratories', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'MDT', "company": 'Medtronic plc', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'SYK', "company": 'Stryker Corporation', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'BSX', "company": 'Boston Scientific Corporation', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'CVS', "company": 'CVS Health Corporation', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'CI', "company": 'The Cigna Group', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'HUM', "company": 'Humana Inc.', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'ELV', "company": 'Elevance Health, Inc.', "exchange": 'NYSE', "sector": 'Healthcare', "asset_type": "STOCK"},
    {"ticker": 'XOM', "company": 'Exxon Mobil Corporation', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'CVX', "company": 'Chevron Corporation', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'COP', "company": 'ConocoPhillips', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'SLB', "company": 'SLB', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'EOG', "company": 'EOG Resources, Inc.', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'MPC', "company": 'Marathon Petroleum Corporation', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'VLO', "company": 'Valero Energy Corporation', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'OXY', "company": 'Occidental Petroleum Corporation', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'PSX', "company": 'Phillips 66', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'KMI', "company": 'Kinder Morgan, Inc.', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'WMB', "company": 'The Williams Companies, Inc.', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'OKE', "company": 'ONEOK, Inc.', "exchange": 'NYSE', "sector": 'Energy', "asset_type": "STOCK"},
    {"ticker": 'NEE', "company": 'NextEra Energy, Inc.', "exchange": 'NYSE', "sector": 'Utilities', "asset_type": "STOCK"},
    {"ticker": 'SO', "company": 'The Southern Company', "exchange": 'NYSE', "sector": 'Utilities', "asset_type": "STOCK"},
    {"ticker": 'DUK', "company": 'Duke Energy Corporation', "exchange": 'NYSE', "sector": 'Utilities', "asset_type": "STOCK"},
    {"ticker": 'D', "company": 'Dominion Energy, Inc.', "exchange": 'NYSE', "sector": 'Utilities', "asset_type": "STOCK"},
    {"ticker": 'AEP', "company": 'American Electric Power Company, Inc.', "exchange": 'NASDAQ', "sector": 'Utilities', "asset_type": "STOCK"},
    {"ticker": 'EXC', "company": 'Exelon Corporation', "exchange": 'NASDAQ', "sector": 'Utilities', "asset_type": "STOCK"},
    {"ticker": 'SRE', "company": 'Sempra', "exchange": 'NYSE', "sector": 'Utilities', "asset_type": "STOCK"},
    {"ticker": 'CEG', "company": 'Constellation Energy Corporation', "exchange": 'NASDAQ', "sector": 'Utilities', "asset_type": "STOCK"},
    {"ticker": 'CAT', "company": 'Caterpillar Inc.', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'DE', "company": 'Deere & Company', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'HON', "company": 'Honeywell International Inc.', "exchange": 'NASDAQ', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'GE', "company": 'GE Aerospace', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'GEV', "company": 'GE Vernova Inc.', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'RTX', "company": 'RTX Corporation', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'LMT', "company": 'Lockheed Martin Corporation', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'NOC', "company": 'Northrop Grumman Corporation', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'GD', "company": 'General Dynamics Corporation', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'BA', "company": 'The Boeing Company', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'UPS', "company": 'United Parcel Service, Inc.', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'FDX', "company": 'FedEx Corporation', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'UNP', "company": 'Union Pacific Corporation', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'CSX', "company": 'CSX Corporation', "exchange": 'NASDAQ', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'NSC', "company": 'Norfolk Southern Corporation', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'ETN', "company": 'Eaton Corporation plc', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'PH', "company": 'Parker-Hannifin Corporation', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'EMR', "company": 'Emerson Electric Co.', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'MMM', "company": '3M Company', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'PWR', "company": 'Quanta Services, Inc.', "exchange": 'NYSE', "sector": 'Industrials', "asset_type": "STOCK"},
    {"ticker": 'PG', "company": 'The Procter & Gamble Company', "exchange": 'NYSE', "sector": 'Consumer Staples', "asset_type": "STOCK"},
    {"ticker": 'KO', "company": 'The Coca-Cola Company', "exchange": 'NYSE', "sector": 'Consumer Staples', "asset_type": "STOCK"},
    {"ticker": 'PEP', "company": 'PepsiCo, Inc.', "exchange": 'NASDAQ', "sector": 'Consumer Staples', "asset_type": "STOCK"},
    {"ticker": 'PM', "company": 'Philip Morris International Inc.', "exchange": 'NYSE', "sector": 'Consumer Staples', "asset_type": "STOCK"},
    {"ticker": 'MO', "company": 'Altria Group, Inc.', "exchange": 'NYSE', "sector": 'Consumer Staples', "asset_type": "STOCK"},
    {"ticker": 'MDLZ', "company": 'Mondelez International, Inc.', "exchange": 'NASDAQ', "sector": 'Consumer Staples', "asset_type": "STOCK"},
    {"ticker": 'CL', "company": 'Colgate-Palmolive Company', "exchange": 'NYSE', "sector": 'Consumer Staples', "asset_type": "STOCK"},
    {"ticker": 'KMB', "company": 'Kimberly-Clark Corporation', "exchange": 'NYSE', "sector": 'Consumer Staples', "asset_type": "STOCK"},
    {"ticker": 'GIS', "company": 'General Mills, Inc.', "exchange": 'NYSE', "sector": 'Consumer Staples', "asset_type": "STOCK"},
    {"ticker": 'KHC', "company": 'The Kraft Heinz Company', "exchange": 'NASDAQ', "sector": 'Consumer Staples', "asset_type": "STOCK"},
    {"ticker": 'AMT', "company": 'American Tower Corporation', "exchange": 'NYSE', "sector": 'Real Estate', "asset_type": "STOCK"},
    {"ticker": 'PLD', "company": 'Prologis, Inc.', "exchange": 'NYSE', "sector": 'Real Estate', "asset_type": "STOCK"},
    {"ticker": 'EQIX', "company": 'Equinix, Inc.', "exchange": 'NASDAQ', "sector": 'Real Estate', "asset_type": "STOCK"},
    {"ticker": 'WELL', "company": 'Welltower Inc.', "exchange": 'NYSE', "sector": 'Real Estate', "asset_type": "STOCK"},
    {"ticker": 'SPG', "company": 'Simon Property Group, Inc.', "exchange": 'NYSE', "sector": 'Real Estate', "asset_type": "STOCK"},
    {"ticker": 'O', "company": 'Realty Income Corporation', "exchange": 'NYSE', "sector": 'Real Estate', "asset_type": "STOCK"},
    {"ticker": 'LIN', "company": 'Linde plc', "exchange": 'NASDAQ', "sector": 'Materials', "asset_type": "STOCK"},
    {"ticker": 'APD', "company": 'Air Products and Chemicals, Inc.', "exchange": 'NYSE', "sector": 'Materials', "asset_type": "STOCK"},
    {"ticker": 'SHW', "company": 'The Sherwin-Williams Company', "exchange": 'NYSE', "sector": 'Materials', "asset_type": "STOCK"},
    {"ticker": 'FCX', "company": 'Freeport-McMoRan Inc.', "exchange": 'NYSE', "sector": 'Materials', "asset_type": "STOCK"},
    {"ticker": 'NEM', "company": 'Newmont Corporation', "exchange": 'NYSE', "sector": 'Materials', "asset_type": "STOCK"},
    {"ticker": 'NUE', "company": 'Nucor Corporation', "exchange": 'NYSE', "sector": 'Materials', "asset_type": "STOCK"},
    {"ticker": 'DOW', "company": 'Dow Inc.', "exchange": 'NYSE', "sector": 'Materials', "asset_type": "STOCK"},
    {"ticker": 'RDDT', "company": 'Reddit, Inc.', "exchange": 'NYSE', "sector": 'Communication Services', "asset_type": "STOCK"},
    {"ticker": 'MSTR', "company": 'Strategy Inc.', "exchange": 'NASDAQ', "sector": 'Technology', "asset_type": "STOCK"},
]
