from __future__ import annotations
from typing import Protocol, AsyncIterator
from datetime import date
from app.domain.models import Quote, PriceBar
from app.prediction.calendar import ReferenceResult


class MarketDataProvider(Protocol):
    async def get_quote(self, ticker: str) -> Quote: ...
    async def get_bars(self, ticker: str, timeframe: str, limit: int) -> list[PriceBar]: ...
    async def get_weekly_reference(self, ticker: str, session_date: date) -> ReferenceResult: ...
    async def list_assets(self) -> list[dict]: ...
    async def stream_quotes(self, tickers: list[str]) -> AsyncIterator[Quote]: ...
